// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmhkHAposlavk7J8pm4C4joS3YoDmSktA',
    appId: '1:725156481458:web:fbb63e21a13c938f6ebcab',
    messagingSenderId: '725156481458',
    projectId: 'restaurant-vendors-app',
    authDomain: 'restaurant-vendors-app.firebaseapp.com',
    storageBucket: 'restaurant-vendors-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADSBG-DLPiRiPo0tS0734r1baPgZGAfok',
    appId: '1:725156481458:android:b3f29f10893b22586ebcab',
    messagingSenderId: '725156481458',
    projectId: 'restaurant-vendors-app',
    storageBucket: 'restaurant-vendors-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8APZaCg8eFELDn8yJnb-zKVSfgBOtrHU',
    appId: '1:725156481458:ios:1ce1181796e394286ebcab',
    messagingSenderId: '725156481458',
    projectId: 'restaurant-vendors-app',
    storageBucket: 'restaurant-vendors-app.appspot.com',
    iosBundleId: 'com.example.vendorApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8APZaCg8eFELDn8yJnb-zKVSfgBOtrHU',
    appId: '1:725156481458:ios:1ce1181796e394286ebcab',
    messagingSenderId: '725156481458',
    projectId: 'restaurant-vendors-app',
    storageBucket: 'restaurant-vendors-app.appspot.com',
    iosBundleId: 'com.example.vendorApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmhkHAposlavk7J8pm4C4joS3YoDmSktA',
    appId: '1:725156481458:web:b09230460c5998596ebcab',
    messagingSenderId: '725156481458',
    projectId: 'restaurant-vendors-app',
    authDomain: 'restaurant-vendors-app.firebaseapp.com',
    storageBucket: 'restaurant-vendors-app.appspot.com',
  );

}